### ISSUE TITLE
Can only inject once

### ISSUE THREAD

**Issue by Sancoraa** [Sumandora/FrameworkCSGO#3]
Hey, nice project you got there !

I'm facing an issue, don't know if it's only from my side though
I can inject fine, but whenever I close the game and relaunch it, I cannot inject anymore, here's the output of ./Load.sh

```
Using 'gdb' to inject
Using 'sudo' for upgrading privileges
2
tee: /proc/sys/kernel/yama/ptrace_scope: Invalid argument
3
Process complete
If you face problems related to the injection process
you should provide the 'gdb.log' and 'build.log' file to whoever is helping you.

```
And here's gdb.log
```
ptrace: Operation not permitted.
No symbol table is loaded.  Use the "file" command.
The program is not being run.
```

I have tried executing ./Unload.sh, rebuilding it, to no avail. Using Arch

**Comment by Sumandora** [comment]
Intended, this line sets the ptrace scope to 3
https://github.com/Sumandora/FrameworkExample/blob/318f36bfff88dd13593e7d5cf088b9176882968f/Load.sh#L88
That means ptrace is disabled until you reboot.
I think this has to be communicated more clearly, I'm going to add something to the readme soon.

Edit: You can comment that line out of course

**Comment by Sancoraa** [comment]
Oh I see, thanks for answering ! I'll close the issue now
